### ISSUE TITLE
What should I install?

### ISSUE THREAD

**Issue by nyngwang** [babel/babel-polyfills#125]
I'm migrating from these:

1. `@babel/plugin-transform-runtime` with `corejs: false`
2. `@babel/preset-env` with `useBuiltIns: 'usage'` and `corejs: 3.21`

to [babel/babel-polyfills](https://github.com/babel/babel-polyfills). I have already installed: `@babel/runtime`,`@babel/plugin-transform-runtime`,`core-js@3`, and `babel-plugin-polyfill-corejs3`.

I want to automatically import polyfills for **my project** and **helpers** when they're needed. So I installed `babel-plugin-polyfill-corejs3` based on the [migration guide on this Repo.](https://github.com/babel/babel-polyfills/blob/main/docs/migration.md), but my question is: do I need to install this one?

```js
yarn add babel-plugin-polyfill-regenerator --dev
```

**Update**:

From my testing I found: **With or without** `['polyfill-regenerator', { method: 'usage-global' }],`, the polyfills for `Promise` are always added. Does it mean that `babel-plugin-polyfill-corejs3` include `babel-plugin-polyfill-regenerator`?

**Comment by nicolo-ribaudo** [comment]
`babel-plugin-polyfill-regenerator` is only needed of you are compiling generators and you want to automatically load `regenerator-runtime` rather than doing it manually. Some people prefer to do it manually to avoid bundlers, but if you are injecting core-js polyfills there is no reason to not use `babel-plugin-polyfill-regenerator`.

Note that if you are not compiling generators, `babel-plugin-polyfill-regenerator` will be a no-op.

**Comment by nicolo-ribaudo** [comment]
Oh actually, `@babel/plugin-transform-runtime` also injects imports to `regenerator-runtime` (because it's a runtime helper, even if it's technically handled as a polyfill) so in your case you don't need `babel-plugin-polyfill-regenerator`.

**Comment by nyngwang** [comment]
@nicolo-ribaudo: Thanks for your reply. I just found that I don't need to install anything further [because the `@babel/preset-env` already includes them](https://github.com/babel/babel/blob/b35ff0f11ca9abccd5acc4914dc3f83db0a53408/packages/babel-preset-env/package.json#L89).
