### ISSUE TITLE
targets property only accepts object

### ISSUE THREAD

**Issue by Fuzzyma** [babel/babel-polyfills#35]
When I use `targets: "> 0.25%, not dead"` for the "polyfill-corejs3" plugin, I get an error: `Invalid Option: '0' is not a valid target`. This also happens when I pass an array (even though I am not sure if this is allowed anyway. 

Passing an object works `{ firefox: 43 }`. Why is a string not working?

Also: I noticed, that my compiled file is still full of code which doesnt fit the target e.g. this one: 

```js
	// Thank's IE8 for his funny defineProperty
	var descriptors = !fails(function () {
	  return Object.defineProperty({}, 1, { get: function () { return 7; } })[1] != 7;
	});
```

I thought the goal of babel-polyfills is to get rid of all this?
Atm, the compiled file is actually bigger than what I had before.

**Comment by agilgur5** [comment]
Just got the same error when passing string `targets` to `polyfill-regenerator` too. `polyfill-regenerator` doesn't even seem to support `targets` per #36 , but still gets the error, so that makes me think it's a bug in the shared helper all the polyfill plugins use, `@babel/helper-define-polyfill-provider`.

It also uses `@babel/helper-compilation-targets` which is used in `@babel/preset-env`, so it's gotta be somewhere in between then. I think the bug would be in [this file](https://github.com/babel/babel-polyfills/blob/3bb29d0b7c18e1baf9227481c03bff20a5854860/packages/babel-helper-define-polyfill-provider/src/index.js), but not totally sure.

**Comment by nicolo-ribaudo** [comment]
Thanks for the report! I opened ad PR to allow strings.

> I thought the goal of babel-polyfills is to get rid of all this?

Yes and no. The goal of `babel-polyfills` is to avoid injecting imports to unnecessary polyfills. However, if a modern polyfill includes an import to some legacy code, there is nothing that we can do about that.

> Atm, the compiled file is actually bigger than what I had before.

Is this compared to core-js 3 with preset-env, or to core-js 2? In the first case it's unexpected, in the second case is because `core-js@3` handles many more edge cases.

**Comment by Fuzzyma** [comment]
> Is this compared to core-js 3 with preset-env, or to core-js 2? In the first case it's unexpected, in the second case is because core-js@3 handles many more edge cases.

Compared to core-js 3

> Yes and no. The goal of babel-polyfills is to avoid injecting imports to unnecessary polyfills. However, if a modern polyfill includes an import to some legacy code, there is nothing that we can do about that.

Is it true that since the polyfill has access to targets now, it should not ship code which is not required? If so, I guess polyfill write needs to catch up first, right?
